# default configuration
baseURL = "/"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "Ying Ge"

# css plugins
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"

[[params.plugins.css]]
URL = "plugins/slick/slick.css"

[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"


# js plugin
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"

[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"

[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"

[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"


# menu
[[menu.main]]
URL = "about"
name = "About"
weight = 2

[[menu.main]]
URL = "blog"
name = "Blog"
weight = 3

[[menu.main]]
URL = "portfolio"
name = "Portfolio"
weight = 4

[[menu.main]]
URL = "contact"
name = "Contact"
weight = 5


# default parameters
[params]
home = "Home"
logo = "images/Ying Doodle.png"
# theme color
theme_color = "#ffb8d4"
email = "me@yinzge.com"
# meta description
author = "Ying Ge"
description = "This is meta description"
# google analitycs
google_analitycs_id = "Your ID"
# copyright
copyright = "&copy; Ying Ge, 2020"
# a theme by [gethugothemes](https://gethugothemes.com)


# contact
[params.contact]
enable = true
form_action = "#" # contact form works with : https://formspree.io

# preloader
[params.preloader]
enable = true
preloader = "" # use png, jpg, svg or gif format

# social site
[[params.social]]
URL = "#"
icon = "ti-facebook"

[[params.social]]
URL = "https://www.instagram.com/yingzge/"
icon = "ti-instagram"

[[params.social]]
URL = "https://www.youtube.com/yingzge"
icon = "ti-dribbble"

[[params.social]]
URL = "#"
icon = "ti-twitter-alt"
